# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: flask_test_app
    build: .
    command: gunicorn -b 0.0.0.0:5000 flask_test_app.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/flask_test_app.db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
    volumes:
      - ./flask_test_app:/code/flask_test_app
      - ./db/:/db/
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq
  redis:
    image: redis
  celery:
    image: flask_test_app
    command: "celery worker -A flask_test_app.celery_app:app"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
